CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     email varchar(64) NOT NULL,
                                     login varchar(32) NOT NULL,
                                     name varchar(32) ,
                                     birthday date,
                                     CONSTRAINT usr_id_pk PRIMARY KEY (id),
                                     CONSTRAINT usr_email_unq UNIQUE (email),
                                     CONSTRAINT usr_login_unq UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS genres (
                                      id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                      name varchar(50) NOT NULL,
                                      CONSTRAINT gnr_id_pk  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS friends (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       owner_id BIGINT REFERENCES users (id),
                                       friend_id BIGINT REFERENCES users (id),
                                       CONSTRAINT frd_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS rating_MPA (
                                          id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                          mpa varchar(8) NOT NULL,
                                          CONSTRAINT rtg_id_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS films (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     title varchar(200) NOT NULL,
                                     description varchar(200) NOT NULL,
                                     release date NOT NULL,
                                     duration INTEGER,
                                     rate INTEGER DEFAULT 0,
                                     mpa_id INTEGER  DEFAULT 1 REFERENCES rating_MPA (id),
                                     CONSTRAINT flm_id_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS film_genres (
                                           id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                                           film_id BIGINT REFERENCES films (id),
                                           genre_id BIGINT REFERENCES genres (id),
                                           CONSTRAINT fg_id_pk  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_liked_film (
                                               user_id BIGINT REFERENCES users (id),
                                               film_id BIGINT REFERENCES films (id)
);